---
kind: pipeline
type: docker
name: wizcli-pipeline

clone:
  disable: false

services:
- name: docker
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run

steps:
- name: docker-build
  image: docker
  commands:
  - docker build -t my-image .
  volumes:
  - name: dockersock
    path: /var/run

- name: authentication
  image: wiziocli.azurecr.io/wizcli:latest
  environment:
    WIZ_POLICY: imsed-cicd-policy
    WIZ_CLIENT_ID:
      from_secret: WIZ_CLIENT_ID
    WIZ_CLIENT_SECRET:
      from_secret: WIZ_CLIENT_SECRET
  commands:
  - /entrypoint auth --id $WIZ_CLIENT_ID --secret $WIZ_CLIENT_SECRET 
  - /entrypoint docker scan -p $WIZ_POLICY --image my-image
  volumes:
  - name: dockersock
    path: /var/run

volumes:
  - name: dockersock
    host:
      path: /var/run




