---
kind: pipeline
type: kubernetes
name: wizcli-pipeline

clone:
  disable: false

steps:
- name: echo-hello
  image: alpine
  commands:
    - echo "Hello, world!"

- name: authentication
  image: wiziocli.azurecr.io/wizcli:latest
  commands:
    - echo "Authenticating"
  environment:
    WIZ_POLICY: imsed-mis-policy
    WIZ_CLIENT_ID:
      from_secret: WIZ_CLIENT_ID
    WIZ_CLIENT_SECRET:
      from_secret: WIZ_CLIENT_SECRET


