kind: pipeline
name: default

steps:
- name: Build
  image: plugins/docker
  network_mode: host
  settings:
    tags: ${DRONE_COMMIT_SHA}
    repo: imsed123/drone
    username:
      from_secret: repo_username
    password:
      from_secret: repo_password
