---
kind: pipeline
type: kubernetes
name: wizcli-pipeline

clone:
  disable: false

steps:
- name: kaniko-build
  image: gcr.io/kaniko-project/executor:latest
  commands:
  - /kaniko/executor --context . --dockerfile Dockerfile --no-push --tarPath /kaniko/my-image.tar

- name: authentication
  image: wiziocli.azurecr.io/wizcli:latest
  commands:
  - /entrypoint auth --id $WIZ_CLIENT_ID --secret $WIZ_CLIENT_SECRET 
  - /entrypoint docker scan  -p $WIZ_POLICY  --image /kaniko/my-image.tar
  environment:
    WIZ_POLICY: imsed-mis-policy
    WIZ_CLIENT_ID:
      from_secret: WIZ_CLIENT_ID
    WIZ_CLIENT_SECRET:
      from_secret: WIZ_CLIENT_SECRET


