---
kind: pipeline
type: docker
name: wizcli-pipeline

clone:
  disable: false

services:
- name: docker
  image: docker:dind

steps:
- name: docker-build
  image: docker
  commands:
  - dockerd-entrypoint.sh &
  - sleep 20
  - docker build -t my-image .

- name: authentication
  image: wiziocli.azurecr.io/wizcli:latest
  environment:
    WIZ_POLICY: imsed-mis-policy
    WIZ_CLIENT_ID:
      from_secret: WIZ_CLIENT_ID
    WIZ_CLIENT_SECRET:
      from_secret: WIZ_CLIENT_SECRET
  commands:
  - /entrypoint auth --id $WIZ_CLIENT_ID --secret $WIZ_CLIENT_SECRET 
  - /entrypoint docker scan -p $WIZ_POLICY --image my-image




