---
kind: pipeline
type: exec
name: wiz-scan

trigger:
  event:
    - pull_request

platform:
  os: linux
  arch: amd64

steps:

- name: Build and scan the image
  commands:
  - | 
    #!/bin/bash
    set -e pipefail
    WIZCLI="/usr/bin/wizcli"
    if ! [ -f $WIZCLI ]; then
        echo "##[command]Obtaining WizCLI from the inter-webs..."
        curl -Lo wizcli https://wizcli.app.wiz.io/latest/wizcli-linux-amd64
        echo "##[command]Making WizCLI executable"
        chmod +x ./wizcli
    fi
    docker build -t ${DRONE_REPO_NAME}:${DRONE_COMMIT_SHA} -f $DOCKER_FILE $CONTEXT
    ./wizcli auth --id $WIZ_CLIENT_ID --secret $WIZ_CLIENT_SECRET
    ./wizcli docker scan --image ${DRONE_REPO_NAME}:${DRONE_COMMIT_SHA} -p $WIZ_POLICY  --driver mountWithLayers
  environment:
    DOCKER_FILE: ./Dockerfile
    CONTEXT: .
    WIZ_POLICY: imsed-cicd-policy
    WIZ_CLIENT_ID:
      from_secret: WIZ_CLIENT_ID
    WIZ_CLIENT_SECRET:
      from_secret: WIZ_CLIENT_SECRET





