kind: pipeline
type: kubernetes
name: wizcli-pipeline

clone:
  disable: false

steps:
- name: docker-build
  image: docker:dind
  commands:  
  - docker build -t my-image .
  environment:
    DOCKER_HOST: tcp://localhost:2375

- name: wizcli-scan
  image: wiziocli.azurecr.io/wizcli:latest
  commands:
  - /entrypoint auth --id $WIZ_CLIENT_ID --secret $WIZ_CLIENT_SECRET 
  - docker save my-image > my-image.tar
  - /entrypoint docker scan  -p $WIZ_POLICY  --image my-image.tar
  environment:
    WIZ_POLICY: imsed-mis-policy
    WIZ_CLIENT_ID:
      from_secret: WIZ_CLIENT_ID
    WIZ_CLIENT_SECRET:
      from_secret: WIZ_CLIENT_SECRET
    DOCKER_HOST: tcp://localhost:2375





