---
kind: pipeline
type: kubernetes
name: wiz-image-scan-k8s

trigger:
  event:
    - pull_request

volumes:
- name: shared
  temp: {}

steps:
- name: kaniko-build
  image: gcr.io/kaniko-project/executor:debug
  commands:  
  - mkdir -p /kaniko/.docker
  - echo '{}' > /kaniko/.docker/config.json
  - /kaniko/executor --context . --dockerfile Dockerfile --destination=dummy --no-push --tarPath /shared/my-image.tar --driver mountWithLayers
  volumes:
  - name: shared
    path: /shared

- name: authentication
  image: wiziocli.azurecr.io/wizcli:latest
  commands:
  - /entrypoint auth --id $WIZ_CLIENT_ID --secret $WIZ_CLIENT_SECRET 
  - /entrypoint docker scan  -p $WIZ_POLICY  --image /shared/my-image.tar
  environment:
    WIZ_POLICY: imsed-cicd-policy
    WIZ_CLIENT_ID:
      from_secret: WIZ_CLIENT_ID
    WIZ_CLIENT_SECRET:
      from_secret: WIZ_CLIENT_SECRET
  volumes:
  - name: shared
    path: /shared




